name: Docs

on:
  push:
    branches:
    - master

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        sudo apt update
        sudo apt install -y libpcap-dev
    - name: Install
      run: |
        pip install -e .[dev]
    - name: Build documentation
      run: |
        make html
      working-directory: ./docs
    - name: Commit documentation changes
      run: |
        git fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin gh-pages
        git worktree add gh-pages gh-pages
        git -C gh-pages rm -rf .
        cp -r docs/_build/html/. gh-pages/
        cd gh-pages
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation to $GITHUB_SHA" -a || true
        # The above command will fail if no changes were present, so we ignore
        # the return code.
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
